sudo: required

services:
  - docker

before_install:
  - docker build -t mustafa78/react-test -f ./client/Dockerfile.dev ./client

script:
  # Run the test container
  - docker run -e CI=true mustafa78/react-test npm test -- --coverage

after_success:
  # Build production version images
  - docker build -t mustafa78/multi-client ./client
  - docker build -t mustafa78/multi-server ./server
  - docker build -t mustafa78/multi-nginx ./nginx
  - docker build -t mustafa78/multi-worker ./worker
  
  # Login to docker cli to associate the docker account with docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them into docker hub
  - docker push mustafa78/multi-client
  - docker push mustafa78/multi-server
  - docker push mustafa78/multi-nginx
  - docker push mustafa78/multi-worker
  